language: go
go:
  - 1.0
install: 
  - cd boot2docker
  - wget https://github.com/boot2docker/boot2docker/releases/download/v.1.1.2/boot2docker.iso 
script: tar -czf  boot2docker_virtualbox.box metadata.json boot2docker.iso 
