language: go
go:
  - 1.0
install: 
  - cd boot2docker
  - wget $(sed -n -e s/\"//g -e s/url\://p metadata.json )
script: tar -czf  boot2docker/metadata.json boot2docker/boot2docker.iso boot2docker_virtualbox.box 
